# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Update npm"
          command: |
            npm install npm@latest
            sudo rm -rf /usr/local/lib/node_modules/npm
            sudo mv node_modules/npm /usr/local/lib/node_modules/npm
            sudo chown -R 500:500 /usr/local/lib/node_modules/npm

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
      - run: npm run report-lcov
      - codecov/upload:
          file: coverage.lcov
   build-docker-tags:
     docker:
       - image: circleci/buildpack-deps:latest
     working_directory: ~/repo
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: build docker image
           command: |
             IMAGE_TAG=${CIRCLE_TAG}
             docker build . -t $IMAGE_NAME:$IMAGE_TAG
       - run:
           name: push docker image
           command: docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  test-all:
    jobs:
      - build
      - build-docker-tags:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

